### ISSUE TITLE
Changing presentation sequence of flashcards

### ISSUE THREAD

**Issue by josephtey** [KevDi/Flashcards#2]
Hi Kevin,
I've been trying to change the presentation sequence (order at which they are being shown), however, am struggling to do so. 

To my understanding, .../flashcardcollection/1/learn/1/wrong?mode=normal, means that the current flashcard being shown can be ANYTHING except the flashcard with ID 1. Is this correct? This seems very difficult to adjust the order for flashcards; where can I find the code in order to change this? I can't seem to understand the part that randomises the sequences, and the part that stops the flashcards after all have been presented. 

What would be the best approach to adjusting the flashcard sequence? 

Thank you so much, looking forward to your response.

**Comment by KevDi** [comment]
If you click learn you should be redirect to the url /flashcardcollection/1/learn?mode=normal.
In this mode a Card out of this collection is choosen randomly. If you click wrong the cards `wrong_answerd` attribute is set to true. If you click right the `right_answered` attribute is set to true. In the `normal` only the cards where both of these Attributes are set to false are selected.
If you click Learn Wrong Ones in the Flashcardcollection only the cards with the `wrong_answered` Attribute set to true are selected. On of these is randomly choosen.

**Comment by josephtey** [comment]
Hi Kevin,
Thanks for your prompt reply, however, where could I find the code to adjust this behaviour? I do not want the flashcards to be presented in this manner, and am unsure of the best approach to alter this. 

Thanks

**Comment by KevDi** [comment]
The Code is located in the `app/main/views.py` file. The Method is called `learn(id)` where id is the ID of the Flashcardcollection

**Comment by josephtey** [comment]
Thank you so much; figured it out now :)
